# Generated by Django 5.2.6 on 2025-09-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
