# Generated by Django 5.2.6 on 2025-10-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('bags', 'Bags'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('balls', 'Balls')], max_length=20),
        ),
    ]
