# Generated by Django 5.2.6 on 2025-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('apparel', 'Apparel'), ('bags', 'Bags'), ('shoes', 'Shoes'), ('equipment', 'Equipment'), ('accessories', 'Accessories')], max_length=20),
        ),
    ]
