# Generated by Django 5.2.6 on 2025-10-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
