# Generated by Django 5.2.8 on 2025-11-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_store_alter_store_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
